# Global configuration file for the project
raw_root: "corpus_raw"
processed_root: "corpus_processed"

# Language settings
# Add new languages here
languages:
  js:
    ts_lang: "javascript"
    file_ext: [".js", ".mjs", ".cjs"]
    tracer: "node-trace"
  python:
    ts_lang: "python"
    file_ext: [".py"]
    tracer: "python-trace"
  html:
    ts_lang: "html"
    file_ext: [".html", ".htm"]
    tracer: "html-trace"
  c:
    ts_lang: "c"
    file_ext: [".c", ".h"]
    tracer: "c-trace"
  java:
    ts_lang: "java"
    file_ext: [".java"]
    tracer: "java-trace"
  cpp:
    ts_lang: "cpp"
    file_ext: [".cpp", ".cc", ".cxx", ".c++", ".hpp", ".hh", ".hxx", ".h++"]
    tracer: "cpp-trace"

# Semiotic classification
semiotic_classification:
  js:
    variable_declaration: { sign_type: "legisign", sign_mode: "index" }
    var: { sign_type: "legisign", sign_mode: "symbol" }
    identifier: { sign_type: "sinsign", sign_mode: "symbol" }
    string: { sign_type: "sinsign", sign_mode: "icon" }
    number: { sign_type: "sinsign", sign_mode: "symbol" }
