# Global configuration file for the project
raw_root: "corpus_raw"
processed_root: "corpus_processed"

# Language settings
# Add new languages here
languages:
  js:
    ts_lang: "javascript"
    file_ext: [".js", ".mjs", ".cjs"]
    tracer: "node-trace"
  python:
    ts_lang: "python"
    file_ext: [".py"]
    tracer: "python-trace"

# Icon settings
icon_rules:
  silence:
    type: "regex"
    pattern: "^[ ]{8,}$"      # 8 連続以上の空白行
  dot_line:
    type: "regex"
    pattern: "^\\.$"          # 行が “.” だけ
  pattern_repeat:
    type: "repeat"
    min_len: 6                # 同一文字 6 連続以上
